### ISSUE TITLE
Build Fails

### ISSUE THREAD

**Issue by bminie** [SpatialTranscriptomicsResearch/std-nb#1]
When trying to run the make command, the build gets to 100% then I receive the errors below. Also, if you attempt to run make debug or make release you get a message similar to as follows: make Nothing to be done for 'release'. If you run the make command from either the debug or release directory, you get the same error state as below.

[ 95%] Built target std
Scanning dependencies of target std-spec-generator
[ 97%] Building CXX object src/spec_generator/CMakeFiles/std-spec-generator.dir/src/spec_generator.cpp.o
[100%] Linking CXX executable std-spec-generator
../spec_parser/libparser-nxt.so: undefined reference to `JIT::Runtime::Builder'
../spec_parser/libparser-nxt.so: undefined reference to `JIT::Runtime::TheModule'
../spec_parser/libparser-nxt.so: undefined reference to `JIT::Runtime::TheContext'
../spec_parser/libparser-nxt.so: undefined reference to `JIT::Runtime::LogErrorV(char const*)'
../spec_parser/libparser-nxt.so: undefined reference to `JIT::Runtime::NamedValues[abi:cxx11]'
collect2: error: ld returned 1 exit status
src/spec_generator/CMakeFiles/std-spec-generator.dir/build.make:106: recipe for target 'src/spec_generator/std-spec-generator' failed
make[3]: *** [src/spec_generator/std-spec-generator] Error 1
CMakeFiles/Makefile2:186: recipe for target 'src/spec_generator/CMakeFiles/std-spec-generator.dir/all' failed
make[2]: *** [src/spec_generator/CMakeFiles/std-spec-generator.dir/all] Error 2
Makefile:151: recipe for target 'all' failed
make[1]: *** [all] Error 2
Makefile:21: recipe for target 'release/.all' failed
make: *** [release/.all] Error 2

**Comment by maaskola** [comment]
Thanks for the error report!
Does that issue still exist with yesterday's commit c4be9a0bc9579cb35fae1cc0997798a390bb4c8a?

**Comment by bminie** [comment]
I actually cloned earlier in the day before that commit. I pulled down again today and now the build error is gone! However, when trying to use the library I am getting a couple of different errors, please see below. I made sure to set my paths in the .bashrc as indicated as well. I can confirm the presence of libtranscriptomedeconvolution-nxt.so and libtranscriptomedeconvolution-nxt-dbg.so in the /usr/local/lib folder. The installation prefix used during the build was /usr/local

$echo $PATH
/usr/local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
$echo $LD_LIBRARY_PATH
/usr/local/lib:

$sudo std-nxt
std-nxt: error while loading shared libraries: libtranscriptomedeconvolution-nxt.so: cannot open shared object file: No such file or directory

**Comment by maaskola** [comment]
Try doing that without the "sudo". Probably the root account does not have /usr/local/lib as part of their LD_LIBRARY_PATH...

**Comment by bminie** [comment]
I tried without the sudo and unfortunately that doesn't work either. Please see the error below:

$std-nxt
terminate called after throwing an instance of 'boost::filesystem::filesystem_error'
  what():  boost::filesystem::create_directory: Permission denied: "std-nxt_2018-10-11T17:55:05.538385Z/"
Aborted (core dumped)

$std-nxt-dbg
terminate called after throwing an instance of 'boost::filesystem::filesystem_error'
  what():  boost::filesystem::create_directory: Permission denied: "std-nxt-dbg_2018-10-11T17:56:27.904483Z/"
Aborted (core dumped)

**Comment by maaskola** [comment]
Looks like the output directory could not be created. I'm guessing the reason for that is that the user executing the command above does not have writing permissions to create the directory in the current working directory.

**Comment by bminie** [comment]
That was it. I'm running this tool in the cloud and changed all directory ownership to the user then the execute worked. I received the error below when executing, is there command line parameters?

$std-nxt
2018-10-15 11:57:01.344726 [info] std-nxt 0.4-2-gc4be9a0 [master branch] - Release build
2018-10-15 11:57:01.344849 [info] Mon Oct 15 11:57:01 2018
2018-10-15 11:57:01.344867 [info] Working directory = /usr/local/bin
2018-10-15 11:57:01.344887 [info] Command = std-nxt
terminate called after throwing an instance of 'std::runtime_error'
  what():  Error: no datasets specified!
Aborted (core dumped)

**Comment by maaskola** [comment]
You got it built!

That message is basically supposed to tell you that you have to specify some data sets. You can consult the command line help with -h / --help.

You can either specify a number of paths to count matrix files in TSV (tab-separated value) format, with genes in rows and spots in columns (otherwise use the --transpose CLI switch).

Or you can use the --design CLI switch and give it a path to a design file. The design file has to have at least one column named "path" which gives that paths to the matrix files you want to use, and can have arbitrary further columns that annotate (categorical) sample information, such as e.g. individual, treatment etc.

**Comment by maaskola** [comment]
Commit 9909cfa introduces a new section in the README.md file with information on how to run the program. Please refer to this section for basic usage instructions.
